"""Add index to book_id in reviews

Revision ID: 643d7af94497
Revises: 72b4056f5918
Create Date: 2025-06-28 11:07:27.016321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643d7af94497'
down_revision: Union[str, Sequence[str], None] = '72b4056f5918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reviews_book_id'), 'reviews', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_book_id'), table_name='reviews')
    # ### end Alembic commands ###
